#
# Rockstar Cryptocurrency Players
#
- name: Dr Craig S Wright
  desc: Alleged creator of Bitcoin
  twitter: ProfFaustus

- name: Roger Ver
  desc: Bitcoin Jesus
  twitter: rogerkver

- name: Jihan Wu
  desc: Co-founder of BITMAIN
  twitter: jihanwu

- name: Ryan X. Charles
  desc: Cofounder & CEO of Yours (http://yours.org )
  twitter: ryanxcharles

- name: Daniel Krawisz
  desc: Nakamoto Institute cofounder (nakamotoinstitute.org)
  twitter: DanielKrawisz

- name: ElectronCash
  desc: Profile run by Otaci for Electron Cash
  twitter: electroncash

- name: Mike Wolf
  desc: OpenBazaar UX designer
  twitter: thee_wolf

- name: Crypt-XO
  desc: Point & Figure Technical Analysis
  twitter: CryptXO

- name: Ant Hill
  desc: Creator of bccaddress.org
  twitter: theantnest

- name: bitsko
  desc: Bitcoin Chat Administrator
  twitter: bitsko

- name: BitAlien
  desc: Libertarian, investor, Bitcoin enthusiast
  twitter: BitAlien_

- name: Samuel Georges
  desc: Armchair analyst and spectator
  twitter: daftspunk
