#
# Rockstar Cryptocurrency Players
#

- name: Dr Craig S Wright
  desc: Inventor of Bitcoin
  twitter: ProfFaustus

- name: Gavin Andresen
  desc: Original lead developer of Bitcoin
  twitter: gavinandresen

- name: Roger Ver
  desc: Bitcoin Jesus
  twitter: rogerkver

- name: Erik Voorhees
  desc: CEO of ShapeShift
  twitter: ErikVoorhees

- name: Jihan Wu
  desc: Co-founder of BITMAIN
  twitter: jihanwu

- name: Deadal Nix
  desc: Bitcoin ABC Developer http://bitcoinabc.org
  twitter: deadalnix

- name: Peter R. Rizun
  desc: Chief Scientist at Bitcoin Unlimited
  twitter: PeterRizun

- name: Andreas M. Antonopoulos
  desc: Bitcoin Evangelist & Conference Speaker
  twitter: aantonop

- name: Daniel Krawisz
  desc: Cofounder of Nakamoto Institute http://nakamotoinstitute.org
  twitter: DanielKrawisz

- name: John McAfee
  desc: Technology Pioneer
  twitter: officialmcafee

- name: Jon Matonis
  desc: Founding Director at Bitcoin Foundation
  twitter: jonmatonis

- name: Jimmy Nguyen
  desc: Comms & Legal Officer at nChain
  twitter: JimmyWinMedia

- name: Ryan X. Charles
  desc: Cofounder & CEO of Yours http://yours.org
  twitter: ryanxcharles

- name: Rob Danielson
  desc: Cofounder of Rocketr http://rocketr.net
  twitter: r0bbot

- name: ElectronCash
  desc: Profile run by Otaci for Electron Cash
  twitter: electroncash

- name: Mike Wolf
  desc: OpenBazaar UX designer
  twitter: thee_wolf

- name: Jimmy Song
  desc: Bitcoin Developer & Entrepreneur
  twitter: jimmysong

- name: Eli Afram
  desc: Developer, Cryptanalyst, Business Analyst
  twitter: justicemate

- name: Ant Hill
  desc: Creator of http://cashaddress.org
  twitter: theantnest

- name: Crypt-XO
  desc: Point & Figure Technical Analysis
  twitter: CryptXO

- name: BitAlien
  desc: Libertarian, investor, Bitcoin enthusiast
  twitter: BitAlien_

- name: James Howells
  desc: Bitcoin Pioneer & Bitcoin Cash Supporter
  twitter: howelzy

- name: Michael Matthews
  desc: Bitcoin Miner & Bitcoin Cash enthusiast
  twitter: mikerelentless

- name: Monte Ohrt
  desc: Programmer & Bitcoin Cash enthusiast
  twitter: mohrt

- name: Brad
  desc: Programmer & Bitcoin Cash enthusiast
  twitter: brad1121

- name: Josh Ellithorpe
  desc: Bitcoin Cash enthusiast
  twitter: zquestz

- name: bitsko
  desc: Bitcoin Cash enthusiast
  twitter: bitsko

- name: Tomothy
  desc: Bitcoin Cash enthusiast
  twitter: tomothyjones

- name: Egon
  desc: Bitcoin Cash enthusiast
  twitter: Egon_01

- name: Mr. Scatman
  desc: Bitcoin Cash enthusiast
  twitter: bsmith12251960

- name: Samuel Georges
  desc: Armchair analyst & spectator
  twitter: daftspunk
