#
# Rockstar Cryptocurrency Players
#
- name: Dr Craig S Wright
  desc: Alleged creator of Bitcoin
  twitter: ProfFaustus

- name: Gavin Andresen
  desc: Original lead developer of Bitcoin
  twitter: gavinandresen

- name: Roger Ver
  desc: Bitcoin Jesus
  twitter: rogerkver

- name: Erik Voorhees
  desc: CEO of ShapeShift
  twitter: ErikVoorhees

- name: Jihan Wu
  desc: Co-founder of BITMAIN
  twitter: jihanwu

- name: Deadal Nix
  desc: Bitcoin ABC Developer http://bitcoinabc.org
  twitter: deadalnix

- name: Peter R. Rizun
  desc: Chief Scientist at Bitcoin Unlimited
  twitter: PeterRizun

- name: Daniel Krawisz
  desc: Cofounder of Nakamoto Institute http://nakamotoinstitute.org
  twitter: DanielKrawisz

- name: John McAfee
  desc: Technology Pioneer
  twitter: officialmcafee

- name: Ryan X. Charles
  desc: Cofounder & CEO of Yours http://yours.org
  twitter: ryanxcharles

- name: Rob Danielson
  desc: Cofounder of Rocketr http://rocketr.net
  twitter: r0bbot

- name: ElectronCash
  desc: Profile run by Otaci for Electron Cash
  twitter: electroncash

- name: Mike Wolf
  desc: OpenBazaar UX designer
  twitter: thee_wolf

- name: Eli Afram
  desc: Developer, Cryptanalyst, Business Analyst
  twitter: justicemate

- name: Ant Hill
  desc: Creator of http://bccaddress.org
  twitter: theantnest

- name: Crypt-XO
  desc: Point & Figure Technical Analysis
  twitter: CryptXO

- name: BitAlien
  desc: Libertarian, investor, Bitcoin enthusiast
  twitter: BitAlien_

- name: bitsko
  desc: Bitcoin Cash enthusiast
  twitter: bitsko

- name: Tomothy
  desc: Bitcoin Cash enthusiast
  twitter: tomothyjones

- name: Egon
  desc: Bitcoin Cash enthusiast
  twitter: Egon_01

- name: Mr. Scatman
  desc: Bitcoin Cash enthusiast
  twitter: bsmith12251960

- name: Samuel Georges
  desc: Armchair analyst & spectator
  twitter: daftspunk
