#
# Rockstar Cryptocurrency Players
#

- name: Dr Craig S Wright
  desc: Very Early Bitcoin Adopter
  twitter: ProfFaustus

- name: Gavin Andresen
  desc: Original Lead Developer of Bitcoin
  twitter: gavinandresen

- name: Vitalik Buterin
  desc: Co-founder of Ethereum Project
  twitter: VitalikButerin

- name: Joseph Lubin
  desc: Co-founder of Ethereum Project
  twitter: ethereumJoseph

- name: Roger Ver
  desc: Bitcoin Jesus
  twitter: rogerkver

- name: Erik Voorhees
  desc: CEO of ShapeShift
  twitter: ErikVoorhees

- name: Peter Smith
  desc: CEO of Blockchain
  twitter: OneMorePeter

- name: Jeff Garzik
  desc: Bitcoin Developer
  twitter: jgarzik

- name: Jihan Wu
  desc: Co-founder of BITMAIN
  twitter: jihanwu

- name: Deadal Nix
  desc: Bitcoin ABC Developer http://bitcoinabc.org
  twitter: deadalnix

- name: Peter R. Rizun
  desc: Chief Scientist at Bitcoin Unlimited
  twitter: PeterRizun

- name: Andreas M. Antonopoulos
  desc: Bitcoin Evangelist & Conference Speaker
  twitter: aantonop

- name: Adam B. Levine
  desc: Host of Let's Talk Bitcoin Podcast
  twitter: GamerAndy

- name: Max Keiser
  desc: Host of The Keiser Report
  twitter: maxkeiser

- name: Daniel Krawisz
  desc: CoFounder of Nakamoto Institute http://nakamotoinstitute.org
  twitter: DanielKrawisz

- name: John McAfee
  desc: Technology Pioneer
  twitter: officialmcafee

- name: Rick Falkvinge
  desc: Founder of the first Pirate Party
  twitter: Falkvinge

- name: Cameron Winklevoss
  desc: CoFounder of Gemini Exchange
  twitter: winklevoss

- name: Tyler Winklevoss
  desc: CoFounder of Gemini Exchange
  twitter: tylerwinklevoss

- name: Micree Zhan
  desc: CEO of BITMAIN
  twitter: MicreeZ

- name: Star Xu
  desc: CEO of OKCoin
  twitter: starokcoin

- name: Jon Matonis
  desc: Founding Director at Bitcoin Foundation
  twitter: jonmatonis

- name: Jimmy Nguyen
  desc: Comms & Legal Officer at nChain
  twitter: JimmyWinMedia

- name: Brian Armstrong
  desc: CoFounder & CEO at Coinbase
  twitter: brian_armstrong

- name: Bitcoin Rush
  desc: Cryptocurrency Journalist
  twitter: Bitcoin_Rush

- name: Ryan X. Charles
  desc: CoFounder & CEO of Yours http://yours.org
  twitter: ryanxcharles

- name: Rob Danielson
  desc: CoFounder of Rocketr http://rocketr.net
  twitter: r0bbot

- name: ElectronCash
  desc: Profile run by Otaci for Electron Cash
  twitter: electroncash

- name: Washington Sanchez
  desc: CoFounder of OpenBazaar
  twitter: drwasho

- name: Sam Patterson
  desc: CoFounder of OpenBazaar
  twitter: SamuelPatt

- name: brian hoffman
  desc: OpenBazaar Project Lead
  twitter: brianchoffman

- name: Mike Wolf
  desc: OpenBazaar UX designer
  twitter: thee_wolf

- name: Jimmy Song
  desc: Bitcoin Developer & Entrepreneur
  twitter: jimmysong

- name: Charlie Shrem
  desc: Bitcoin Pioneer & Bitcoin Supporter
  twitter: CharlieShrem

- name: Eli Afram
  desc: Developer, Cryptanalyst, Business Analyst
  twitter: justicemate

- name: Ant Hill
  desc: Creator of http://cashaddress.org
  twitter: theantnest

- name: Crypt-XO
  desc: Point & Figure Technical Analysis
  twitter: CryptXO

- name: BitAlien
  desc: Libertarian, investor, Bitcoin enthusiast
  twitter: BitAlien_

- name: James Howells
  desc: Bitcoin Pioneer & Bitcoin Cash Supporter
  twitter: howelzy

- name: Michael Matthews
  desc: Bitcoin Miner & Bitcoin Cash enthusiast
  twitter: mikerelentless

- name: Monte Ohrt
  desc: Programmer & Bitcoin Cash enthusiast
  twitter: mohrt

- name: Brad
  desc: Programmer & Bitcoin Cash enthusiast
  twitter: brad1121

- name: Josh Ellithorpe
  desc: Bitcoin Cash enthusiast
  twitter: zquestz

- name: bitsko
  desc: Bitcoin Cash enthusiast
  twitter: bitsko_xt

- name: Tomothy
  desc: Bitcoin Cash enthusiast
  twitter: tomothyjones

- name: Egon
  desc: Bitcoin Cash enthusiast
  twitter: Egon_01

- name: Mr. Scatman
  desc: Bitcoin Cash enthusiast
  twitter: bsmith12251960

- name: Samuel Georges
  desc: Bitcoin Cash enthusiast
  twitter: daftspunk
